site_name: 'MPP Documentation'
repo_url: https://github.com/bankservafrica/rpi-portal-docs-backstage
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Tables: tables.md
  - 'AVS Examples': examples.md
  - 'AVS Scenarios': scenarios.md
  - 'AVS Flow Diagrams': Diagrams/Verification.md
  - 'AVSB Flow Diagrams': Diagrams/AVS_BatchFlows.md
  - 'RTC Examples': RTCexamples.md
  - 'RTC Flow Diagram': Diagrams/RTC.md
  - 'RTC Mapping BICISO to JSON(verification)': Mapping/BICISO-JSON(verification).md
  - 'RTC Mapping BICISO to JSON(clearing)': Mapping/BICISO-JSON(clearing).md
  - 'RTC Mapping JSON to BICISO(verification)': Mapping/JSON-BICISO(verification).md
  - 'RTC Mapping JSON to BICISO(verification response)': Mapping/JSON-BICISO(verification-response).md
  - 'RTC Mapping JSON to BICISO(clearing)': Mapping/JSON-BICISO(clearing).md
  - 'RTC Mapping JSON to BICISO(clearing response)': Mapping/JSON-BICISO(clearing-response).md

plugins:
  - techdocs-core