site_name: 'MPP Documentation'
repo_url: https://github.com/ShazBSA/rpi-portal-docs
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Tables: tables.md
  - 'AVS Examples': examples.md
  - 'AVS Scenarios': scenarios.md
  - 'AVS Flow Diagrams': Diagrams/Verification.md
  - 'AVSB Flow Diagrams': Diagrams/AVS_BatchFlows.md
  - 'RTC Flow Diagram': Diagrams/RTC.md

plugins:
  - techdocs-core